services:
  web:
    image: ghcr.io/yogianggara129/intervai-web:sha-PENDING
    container_name: intervai-web
    restart: unless-stopped
    networks:
      - proxy

  api:
    image: ghcr.io/yogianggara129/intervai-api:sha-PENDING
    container_name: intervai-api
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy